version: '2'
services:
    djgateway-app:
        image: djgateway
        external_links:
            - djgateway-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - djgateway-cassandra:cassandra
            - djgateway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/djgateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    djgateway-postgresql:
        extends:
            file: postgresql.yml
            service: djgateway-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: djgateway-cassandra
    djgateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: djgateway-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
