version: '2'
services:
    djgateway-cassandra:
        container_name: djgateway-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/djgateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    djgateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: djgateway-cassandra-migration
        links:
            - djgateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
